"""Core iterative generation workflow."""

from dataclasses import dataclass
from pathlib import Path
import re
import secrets
from typing import Protocol

from langchain_openai import ChatOpenAI

from .config import Settings
from .simulation import SimulationResult, simulate_code


class LanguageModel(Protocol):
    def invoke(self, input: str): ...


@dataclass(frozen=True)
class RunResult:
    path: Path
    iterations: int
    goals_satisfied: bool
    simulation: SimulationResult | None = None


def clean_code_block(code: str) -> str:
    code = code.strip()
    match = re.fullmatch(r"```(?:python)?\s*\n?(.*?)\n?```", code, flags=re.DOTALL | re.IGNORECASE)
    return (match.group(1) if match else code).strip()


def to_snake_case(text: str, max_length: int = 40) -> str:
    value = re.sub(r"[^a-zA-Z0-9]+", "_", text).strip("_").lower()
    return value[:max_length].rstrip("_") or "generated"


class CodeAgent:
    def __init__(self, llm: LanguageModel, output_dir: Path | str = "generated") -> None:
        self.llm = llm
        self.output_dir = Path(output_dir)

    @classmethod
    def from_settings(cls, settings: Settings, output_dir: Path | str = "generated") -> "CodeAgent":
        llm = ChatOpenAI(
            model=settings.model,
            temperature=0.3,
            api_key=settings.api_key,
            base_url=settings.base_url,
        )
        return cls(llm, output_dir)

    @staticmethod
    def _goals_text(goals: list[str]) -> str:
        return "\n".join(f"- {goal}" for goal in goals)

    def generate_prompt(self, use_case: str, goals: list[str], previous_code: str = "", feedback: str = "") -> str:
        prompt = f"""You are an AI coding agent.

Write complete, runnable Python code for this use case:
{use_case}

Goals:
{self._goals_text(goals)}
"""
        if previous_code:
            prompt += f"\nPreviously generated code:\n{previous_code}\n"
        if feedback:
            prompt += f"\nReview feedback to address:\n{feedback}\n"
        return prompt + "\nReturn only Python code, without Markdown fences or explanations."

    def review(self, code: str, goals: list[str], simulation_feedback: str = "") -> str:
        prompt = f"""You are a senior Python reviewer. Evaluate the code for correctness,
simplicity, readability, edge cases, bugs, and compliance with every goal.

Goals:
{self._goals_text(goals)}

Code:
{code}

Local test results:
{simulation_feedback or "No local simulation was requested."}

Explain what is correct and what must improve."""
        return self._content(self.llm.invoke(prompt))

    def goals_met(self, feedback: str, goals: list[str]) -> bool:
        prompt = f"""Decide whether all important goals are satisfied based only on this review.

Goals:
{self._goals_text(goals)}

Review:
{feedback}

Respond with exactly True or False."""
        return self._content(self.llm.invoke(prompt)).strip().casefold() == "true"

    @staticmethod
    def _content(response: object) -> str:
        content = getattr(response, "content", response)
        if not isinstance(content, str):
            raise TypeError("The language model returned non-text content")
        return content.strip()

    def save(self, code: str, use_case: str) -> Path:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{to_snake_case(use_case)}_{secrets.token_hex(2)}.py"
        path = self.output_dir / filename
        header = f"# Generated by AI Code Agent\n# Use case: {use_case.strip()}\n\n"
        path.write_text(header + code + "\n", encoding="utf-8")
        return path

    def run(
        self,
        use_case: str,
        goals: list[str],
        max_iterations: int = 5,
        initial_code: str = "",
        review_first: bool = False,
        simulate: bool = False,
        test_arguments: list[str] | None = None,
        test_input: str = "",
        simulation_timeout: float = 10.0,
    ) -> RunResult:
        use_case = use_case.strip()
        goals = [goal.strip() for goal in goals if goal.strip()]
        if not use_case:
            raise ValueError("Use case must not be empty")
        if not goals:
            raise ValueError("At least one goal is required")
        if max_iterations < 1:
            raise ValueError("max_iterations must be at least 1")
        if review_first and not initial_code.strip():
            raise ValueError("review_first requires initial_code")

        code = ""
        previous_code = initial_code.strip()
        feedback = ""
        satisfied = False
        simulation_result = None
        for iteration in range(1, max_iterations + 1):
            if iteration == 1 and review_first:
                code = previous_code
            else:
                prompt = self.generate_prompt(use_case, goals, previous_code, feedback)
                code = clean_code_block(self._content(self.llm.invoke(prompt)))
            if not code:
                raise RuntimeError("The language model returned empty code")
            simulation_result = (
                simulate_code(code, test_arguments, test_input, simulation_timeout)
                if simulate
                else None
            )
            simulation_feedback = simulation_result.as_feedback() if simulation_result else ""
            feedback = self.review(code, goals, simulation_feedback)
            satisfied = (simulation_result is None or simulation_result.success) and self.goals_met(
                feedback, goals
            )
            if satisfied:
                break
            previous_code = code

        return RunResult(self.save(code, use_case), iteration, satisfied, simulation_result)
